# SPDX-License-Identifier: GPL-3.0-or-later
name: EvictiCloud
options:
  bundleIdPrefix: com.rishmadaan
  deploymentTarget:
    macOS: "14.0"
  createIntermediateGroups: true
settings:
  base:
    SWIFT_VERSION: "5.9"
    CODE_SIGN_IDENTITY: "-"
    CODE_SIGN_STYLE: Manual
    MACOSX_DEPLOYMENT_TARGET: "14.0"
targets:
  EvictiCloud:
    type: application
    platform: macOS
    sources:
      - path: EvictiCloud
      - path: Shared
      - path: LICENSE
        buildPhase: resources
    entitlements:
      path: EvictiCloud/EvictiCloud.entitlements
      properties:
        com.apple.security.app-sandbox: true
        com.apple.security.files.user-selected.read-only: true
    info:
      path: EvictiCloud/Info.plist
      properties:
        CFBundleDisplayName: Evict iCloud
        NSHumanReadableCopyright: "Copyright (c) 2025-2026 Rishabh Madaan"
        LSApplicationCategoryType: public.app-category.utilities
  EvictiCloudTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - path: Tests
      - path: Shared
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
schemes:
  EvictiCloud:
    build:
      targets:
        EvictiCloud: all
    test:
      targets:
        - EvictiCloudTests
